version: "3"

services:
  dexie-sync-backend:
    build: https://github.com/christian-german/dexie-sync-backend.git
    image: dexie-sync-backend

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dexie
